{% set name = "kubernetes-helm" %}
{% set version = "2.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/helm/archive/v{{ version }}.tar.gz  # [not win]
  url: https://storage.googleapis.com/{{ name }}/helm-v{{ version }}-windows-amd64.tar.gz  # [win]

  sha256: 7ca0a045c7f2927a934f2d516b87f19af5f10ac767b0aa3a73deac7b218b5751  # [not win]
  sha256: 7a29c35b19cf9070e3950524cf04b8848f257535e00ea5fc45a80916ab253981  # [win]

build:
  skip: True  # [win32]
  number: 1000

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - {{ compiler('c') }}
    - make  # [not win]
  host:
    - git  # [not win]
    - mercurial  # [not win]

test:
  commands:
    - helm --help
    - tiller -version  # [linux]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/kubernetes/helm

extra:
  recipe-maintainers:
    - sodre
