{% set goname = "k8s.io/helm" %}
{% set version = "2.12.2" %}


{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/helm/helm
  git_tag: v{{ version }}

build:
  number: 1000
  script:
    - pushd {{ pkg_src }}
    - go install -v cmd/...

requirements:
  build:
    - {{ compiler('go') }}  # [not win]

test:
  commands:
    - helm --help
    - tiller -version  # [linux]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
