{% set name = "kubernetes-helm" %}
{% set version = "2.9.1" %}

{% set sha256 = "2fee31764117024d1cc4f597d23791c60feef7c3ceedd143cfdbbafca7a7e126" %}
{% set sha256_win64 = "4db0f889051f18fa9b65d1ba8172153a3a6dc1e0efa640865b290ee352552d92" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/helm/archive/v{{ version }}.tar.gz  # [not win]
  url: https://storage.googleapis.com/{{ name }}/helm-v{{ version }}-windows-amd64.tar.gz  # [win]

  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}  # [not win]
  sha256: {{ sha256_win64 }}  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - go 1.9.*  # [not win]
    - git  # [not win]
    - make  # [not win]
    - mercurial  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - helm --help 

    # ugly hack because cloud-controller-manager is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/kubernetes/helm

extra:
  recipe-maintainers:
    - sodre
