{% set goname = "k8s.io/helm" %}
{% set version = "2.13.1" %}


{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    git_url: https://github.com/helm/helm  # [unix]
    git_tag: v{{ version }}                # [unix]
    url: https://storage.googleapis.com/kubernetes-{{ name }}/{{ name }}-v{{ version }}-windows-amd64.tar.gz  # [win]
    sha256: fc810c306526197dce1d43068bc6385dad13b9d86e912bfd79fc06fe9d275a3d  # [win]

build:
  number: 1000
  script:
    - pushd {{ pkg_src }}
    - make bootstrap build test-unit  # [unix]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}
    - cp tiller{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }}
    - go-glide
    - go-gox

test:
  commands:
    - helm --help
    - tiller -version

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
