{% set name = "kubernetes-helm" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/helm/archive/v{{ version }}.tar.gz  # [not win]
  url: https://storage.googleapis.com/{{ name }}/helm-v{{ version }}-windows-amd64.tar.gz  # [win]

  fn: {{ name }}-{{ version }}.tar.gz
  sha256: eee403cc1e05ab2eb1c6802eb7ecc4a5c544cb5971b7ee828c0b8d60fe061eb0  # [not win]
  sha256: 8347dc5ea12d937eb793ed438ea3274f40639144abdc8b071715937aad8a7616  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - make  # [not win]
    - {{ compiler('c') }}
  host:
    - go 1.9.*  # [not win]
    - git  # [not win]
    - mercurial  # [not win]

test:
  commands:
    - helm --help

    # ugly hack because cloud-controller-manager is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/kubernetes/helm

extra:
  recipe-maintainers:
    - sodre
