{% set name = "kubernetes-helm" %}
{% set version = "2.10.0" %}

{% set sha256 = "9bd32dae4b4631480782904dd79a6c942803a4e1c8974072d39aed2a74fca86c" %}
{% set sha256_win64 = "e8626ad091b23284cbbe30851f665868292e7b788052981cc4c4a585808d4834" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/helm/archive/v{{ version }}.tar.gz  # [not win]
  url: https://storage.googleapis.com/{{ name }}/helm-v{{ version }}-windows-amd64.tar.gz  # [win]

  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}  # [not win]
  sha256: {{ sha256_win64 }}  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - make  # [not win]
    - {{ compiler('c') }}
  host:
    - go 1.9.*  # [not win]
    - git  # [not win]
    - mercurial  # [not win]

test:
  commands:
    - helm --help

    # ugly hack because cloud-controller-manager is not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/kubernetes/helm

extra:
  recipe-maintainers:
    - sodre
