{% set goname = "k8s.io/helm" %}
{% set version = "2.12.2" %}


{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    git_url: https://github.com/helm/helm
    git_tag: v{{ version }}

build:
  number: 1000
  script:
    - pushd {{ pkg_src }}
    - make bootstrap build test-unit
    - mkdir {{ target_gobin }}
    - cp bin/helm{{ target_goexe }} {{ target_gobin }}
    - cp bin/tiller{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }}
    - make
    - m2-make  # [win]
    - go-glide
    - go-gox

test:
  commands:
    - helm --help
    - tiller -version

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
